name: Daily Data Pipeline

on:
  schedule:
    - cron: '0 9 * * *'  # Запуск каждый день в 09:00 UTC = 12:00 МСК
  workflow_dispatch:     # Позволяет запускать вручную

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests supabase

      - name: Run fetch_data.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python Pet/fetch_data.py
